- src/Authentication/Authentication.php
- tests/Authentication/AuthenticationTest.php
```
$ vendor/bin/phpunit tests/Authentication/AuthenticationTest.php
PHPUnit 9.5.20 #StandWithUkraine
Runtime:       PHP 8.0.18
Configuration: /Users/kenji/work/codeigniter/codeigniter-shield/phpunit.xml
Random Seed:   1650351079
EE                                                                  2 / 2 (100%)
Time: 00:00.080, Memory: 12.00 MB
There were 2 errors:
1) Tests\Authentication\AuthenticationTest::testThrowsOnUnknownHandler
ErrorException: SQLite3::query(): Unable to prepare statement: 1, no such table: db_settings
/Users/kenji/work/codeigniter/codeigniter-shield/vendor/codeigniter4/framework/system/Database/SQLite3/Connection.php:116
/Users/kenji/work/codeigniter/codeigniter-shield/vendor/codeigniter4/framework/system/Database/BaseConnection.php:670 …
```
> test: fix AuthenticationTest

- src/Authentication/Passwords.php
- src/Authentication/Passwords/BaseValidator.php
- src/Controllers/RegisterController.php
- tests/Unit/CompositionValidatorTest.php
- tests/Unit/DictionaryValidatorTest.php
- tests/Unit/NothingPersonalValidatorTest.php
- tests/Unit/PwnedValidatorTest.php
`ValidatorInterface` does not have `setConfig()`.
All Validator classes require the Config and there is no necessity to set it later.
> refactor: remove BaseValidator::setConfig()

- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Authentication/Handlers/Session.php
- tests/Authentication/ChainFilterTest.php
- tests/Authentication/SessionFilterTest.php
- tests/Authentication/TokenFilterTest.php
- use Interface methods instead of methods in concrete classes
Fixes 12 errors of 35: https://github.com/lonnieezell/codeigniter-shield/pull/44#issuecomment-1105787493
> refactor: use Interface methods

- src/Models/UserIdentityModel.php
We should add `order by` if we expect the same result in any environment.
> fix: add `order by` in UserIdentityModel

- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Exceptions/LogicException.php
- src/Exceptions/RuntimeException.php
- add User null check
- add check to see if the email sent
> Add error checks in Actions

- src/Authentication/Actions/EmailActivator.php
~~Needs to rebase after merging #110~~
- add null check for email address
> Add email null check

- docs/2 - authentication.md
- docs/5 - events.md
- src/Auth.php
- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Authentication/AuthenticatorInterface.php
- src/Authentication/Authenticators/AccessTokens.php
- src/Authentication/Authenticators/Session.php
- src/Authentication/Traits/HasAccessTokens.php
- src/Controllers/LoginController.php
- src/Controllers/RegisterController.php
- src/Entities/User.php
- src/Language/en/Auth.php
- src/Models/UserModel.php
- src/Views/email_activate_show.php
- tests/Authentication/SessionAuthenticatorTest.php
- tests/Controllers/RegisterTest.php
Supersedes  #99
- fix Event names: now `failedLogin`, `login`, `logout`, `register`
- `login` is fired only once after login process is completed
- fix error invalidActivateToken does not show
- change return types
- add `Auth::activateUser()` and `UserModel::activate()`
- refactor
> fix: Event triggers

- src/Authentication/Actions/ActionInterface.php
- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Authentication/Authenticators/AccessTokens.php
- src/Authentication/Authenticators/Session.php
- src/Config/Auth.php
- src/Controllers/ActionController.php
- src/Controllers/RegisterController.php
- src/Filters/SessionAuth.php
- src/Views/email_2fa_show.php
- tests/Authentication/AuthHelperTest.php
- tests/Authentication/SessionAuthenticatorTest.php
- tests/Controllers/ActionsTest.php
- add `$userState` in `Session`
- now `Session::loggedIn()` does not return `true` for pending login user.
- now `Session::getUser()` does not return pending login user, so `auth()->user()` also does not return.
- add `Session::getPendingUser()`
- add `Session::isPending()` that returns `true` when a user is in pending login state.
- add `Session::isAnonymous()`
- add `ActionInterface::getType()`
- refactor
> Add User State in Authenticators\Session

- src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
- tests/Authentication/HasAccessTokensTest.php
Access Token or Magic Link Token must be unique.
> fix: add missing unique key to `auth_identities`

- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Authentication/Authenticators/Session.php
- src/Authentication/Traits/HasAccessTokens.php
- src/Authorization/Traits/Authorizable.php
- src/Controllers/MagicLinkController.php
- src/Entities/User.php
- src/Models/GroupModel.php
- src/Models/PermissionModel.php
- src/Models/RememberModel.php
- src/Models/UserIdentityModel.php
- tests/Authentication/SessionAuthenticatorTest.php
Changes classes to prefer whole-object parameters instead of the less-precise `int|string` ID.
Fixes #66.
> Refactor: Object Parameters

- src/Authentication/Actions/Email2FA.php
- src/Authentication/Authenticators/Session.php
- src/Config/Auth.php
- src/Controllers/ActionController.php
- src/Controllers/RegisterController.php
- src/Models/UserIdentityModel.php
- tests/Authentication/AuthHelperTest.php
- tests/Authentication/ChainFilterTest.php
- tests/Authentication/MagicLinkTest.php
- tests/Authentication/SessionAuthenticatorTest.php
- tests/Authentication/SessionFilterTest.php
- tests/Controllers/ActionsTest.php
- tests/Controllers/LoginTest.php
- change the session variable structure:
- now uses one key
```php
[
'user' => [
'auth_action' => 'CodeIgniter\Shield\Authentication\Actions\Email2FA',
'auth_action_message' => 'You must complete a two-factor verification.',
'id' => '1',
]
]
```
- if there are more than one identity for actions, use the first one.
- if session has the user info, use it to check the user state.
- add code to set `auth_action` after checking valid remember-me token.
- refactor
> refactor: change session variable

- src/Authentication/Actions/Email2FA.php
- src/Authentication/Authenticators/Session.php
- src/Controllers/RegisterController.php
- src/Test/AuthenticationTesting.php
- tests/Controllers/ActionsTest.php
~~Needs to rebase after merging #145~~
- `Session::login()` will complete authentication, or throws Exception if there is auth action.
- `Session::login()` fires `login` event.
- add parameter `$pending` to `actingAs()` for pending login.
> fix: Session::login() method behavior

- src/Language/fa/Auth.php
> fix: add missing `Auth.registerSuccess` for farsi

- src/Authentication/Authenticators/Session.php
- src/Entities/User.php
`$session->get()` does not return all `$_SESSION` items (flashdata and tempdata are excluded), 
but I think this change is fine.
> refactor: remove $_SESSION

- composer.json
Removes the unused `repositories` key which may be contributing to the GitHub Actions workflow failures.
> Composer Repositories

- .github/workflows/phpcpd.yml
- src/Authentication/Authenticators/AccessTokens.php
- src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
- src/Models/LoginModel.php
- src/Models/TokenLoginModel.php
- tests/Authentication/AccessTokenAuthenticatorTest.php
- add `auth_token_logins` table to record Bearer Token type login attempts
- use `auth_token_logins` in AccessTokens Authenticator
- fix `auth_token` column type to not null
- refactor
> feat: add `auth_token_logins` table

- src/Entities/User.php
- src/Models/LoginModel.php
- tests/Unit/UserTest.php
Fixes #155
- returns the last successful login in the `auth_logins` table of the user
- refactor
- ~~When `$allowFailed` is false, returns the last successful login in the `auth_logins` table~~
- ~~When `$allowFailed` is true, finds the last login by email or username in the `auth_logins` table~~
> fix: lastLogin()

- src/Authentication/Authenticators/Session.php
- src/Authentication/Traits/HasAccessTokens.php
- src/Models/GroupModel.php
- src/Models/PermissionModel.php
- src/Models/UserIdentityModel.php
- src/Models/UserModel.php
The return type of write-type query methods are not unified. 
Failures of writing to database are abnormal things, so Exceptions should be thrown.
- change return type to `void`
- add query return value checks
> If you forget to check an error, you’ll get silent bugs. Unchecked error values are worse than uncaught exceptions.
https://programmingduck.com/articles/exceptions-error-values
> fix: Models return type

- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Authentication/Authenticators/AccessTokens.php
- src/Authentication/Authenticators/Session.php
- src/Controllers/MagicLinkController.php
- src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
- src/Entities/User.php
- src/Models/CheckQueryReturnTrait.php
- src/Models/LoginModel.php
- src/Models/UserIdentityModel.php
- src/Models/UserModel.php
- tests/Authentication/AccessTokenAuthenticatorTest.php
- tests/Authentication/MagicLinkTest.php
- tests/Controllers/ActionsTest.php
- tests/Controllers/RegisterTest.php
- tests/Unit/LoginModelTest.php
- tests/Unit/UserIdentityModelTest.php
- tests/Unit/UserTest.php
~~Need to rebase after merging  #177~~
Identifiers can be added, and it will be not possible to determine what they are just from the identifier string.
Currently, `token: ` is also added to access tokens. 
Also, if there is no constraint, it is not possible to tell whether it is an `email` or a `username` just from the string.
It is easier to know what it is if we add a column for identifier type.
- add `id_type` in `auth_logins` and `auth_token_logins`
- type: `email_password`, `username`, `magic-link`, and `access_token`
- add validation error check in `CheckQueryReturnTrait`
- add const `ID_TYPE_*` in `Session` and `AccessTokens`
> feat: add `id_type` in logins table

- src/Authentication/Authenticators/AccessTokens.php
session helper does not exist.
> refactor: remove `helper('session')`

- src/Authentication/AuthenticatorInterface.php
- src/Authentication/Authenticators/AccessTokens.php
- src/Authentication/Authenticators/Session.php
- nobody checks the return value of `logout()`
- normally, the logout process cannot fail.
-  if something is wrong, it should throw an Exception.
- `Events::trigger()` may return false, but it does not mean errors.
- when one listener returns false, the execution of listeners stops.
- https://github.com/codeigniter4/CodeIgniter4/blob/ad956b426a1595a490f6b83b9e74338e0eb219e4/system/Events/Events.php#L149-L161
> refactor: change logout() return type to void

- docs/0 - install.md
Actually the class has the following `use`:
```php
use CodeIgniter\Config\BaseConfig;
use CodeIgniter\Shield\Authentication\Actions\ActionInterface;
use CodeIgniter\Shield\Authentication\AuthenticatorInterface;
use CodeIgniter\Shield\Authentication\Authenticators\AccessTokens;
use CodeIgniter\Shield\Authentication\Authenticators\Session;
use CodeIgniter\Shield\Authentication\Passwords\ValidatorInterface;
use CodeIgniter\Shield\Models\UserModel;
use CodeIgniter\Shield\Config\Auth as ShieldAuth;
```
> docs: improve sample code in `0 - install.md`

- src/Authentication/Authenticators/Session.php
- tests/Collectors/AuthTest.php
Fixes #210
- fix: update `$this->userState` when logout
- remove unneeded helper loading
> fix: Debugbar error after logout 

- src/Controllers/LoginController.php
- tests/Controllers/LoginTest.php
Hello, my hardworking friends.
When the user `loggedIn`, if he calls the `/login` form again, **the form will be displayed!**
This is completely meaningless.
Suggestions came to my mind.
1. Display the message "You are already logged in."
2. User logout if this happens.
3. User transfer to `config('Auth')->loginRedirect()`.
**I chose option 3.**
what is your idea about this?
> fix: redirect user if `loggedIn()` and called `/login` page

- src/Authentication/Authenticators/Session.php
- tests/Authentication/Authenticators/SessionAuthenticatorTest.php
- fix missing `Cookie.prefix`
- fix hard coded cookie name `remember`
> fix: RememberMe cookie does not work with Cookie prefix

- src/Authentication/Authenticators/Session.php
- tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Reported in https://github.com/codeigniter4/shield/issues/214#issuecomment-1150421000
- fix `Session::loggedIn()` returns wrong result when the user was deleted.
**Steps to Reproduce:**
1. register a user
2. login as the user with remember me
3. delete the user from the database
4. access the site
> fix: error occurs if a user deleted from the database has session User Info or RememberMe cookie

- src/Controllers/MagicLinkController.php
- tests/Controllers/MagicLinkTest.php
Hello good guys
Ref: #215 
It seems that changes should have been made here as well.
> fix: redirect user after `loggedIn()` and called `/login/magic-link` page

- src/Commands/Setup.php
- tests/Commands/SetupTest.php
> fix: `use` is missing in the replaced source files

- src/Authentication/Authenticators/Session.php
- tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Basically, a logged-in user is not supposed to log in again without logging out, 
and should be protected so that he/she cannot do so with filters and/or controllers.
But a developer may misconfigure and if a logged-in user logs in with a different user account, 
the session data of the previous user is carried over.
This PR prevents such behavior by making errors.
> feat: prevent logged-in users from trying to log in again

- src/Authentication/Authenticators/Session.php
- tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Fixes #225
`Session::logout()` does not work if only `Session::logout()` is called.
> fix: `Session::logout()` does not work

- src/Authentication/Passwords/NothingPersonalValidator.php
- src/Controllers/RegisterController.php
- src/Models/UserModel.php
- tests/Unit/NothingPersonalValidatorTest.php
> fix: workaround for email only registration/login

- docs/0 - install.md
Fixes #240
- add note about `Class "SQLite3" not found` error
> docs: improve installation

- src/Authentication/Authenticators/AccessTokens.php
- src/Authorization/Traits/Authorizable.php
- src/Controllers/MagicLinkController.php
- src/Models/LoginModel.php
- src/Models/TokenLoginModel.php
- tests/Authorization/AuthorizableTest.php
When `toDateTimeString() ` is used. If `defaultLocale = 'fa'`.
The value of the datetime will be `UTF-8 string (33) "۲۰۲۲-۰۶-۱۲ ۲۲:۳۰:۳۵"`.
In this case, the database enters the information as `0000-00-00 00:0:00`.
Which causes a bug in the shield.
In this PR I tried to solve this problem.
note: This method can also solve the problem. `$time = new Time('now','','en-US') `
```
Data of Table "auth_groups_users":
+----+---------+-------+--------------------+
| id | user_id | group | created_at         |
+----+---------+-------+--------------------+
| 7  | 7       | user  | 0000-00-00 00:0... |
| 22 | 22      | user  | 0000-00-00 00:0... |
| 23 | 23      | user  | 2022-06-12 19:3... |
+----+---------+-------+--------------------+
```
> fix: datetime for defaultLocale set fa

- docs/quickstart.md
- src/Authorization/Traits/Authorizable.php
- tests/Authorization/AuthorizableTest.php
- Standardize variadic passing of groups/permissions to the syncGroups and syncPermissions methods.
- Added docs for groups to the quick start.
Replaces #256
> Use variadic passing of groups/permissions

- src/Language/fr/Auth.php
- tests/Language/AbstractTranslationTestCase.php
- tests/Language/FrenchTranslationTest.php
If @includebeer sees any changes to be made, don't hesitate.
> Add French translations

- .github/workflows/phpunit-lang.yml
- phpunit.xml.dist
-  add language unit tests workflow
I tested on my repository: https://github.com/kenjis/codeigniter-shield/pull/1
```
Run vendor/bin/phpunit --verbose --no-coverage --testsuite lang
PHPUnit 9.5.21 #StandWithUkraine
Runtime:       PHP 8.0.20
Configuration: /home/runner/work/codeigniter-shield/codeigniter-shield/phpunit.xml.dist
Random Seed:   1656800527
.....................                                             21 / 21 (100%)
Time: 00:00.026, Memory: 10.00 MB
OK (21 tests, 21 assertions)
```
> chore: add language unit tests

- src/Views/email_2fa_show.php
- src/Views/email_2fa_verify.php
- src/Views/login.php
- src/Views/magic_link_form.php
- src/Views/register.php
- tests/Authentication/MagicLinkTest.php
Fixes #267
- Replaced `route_to()` by `url_to()` in the views, when is was used alone.
- When `route_to()` was used with `site_url()`, as in `site_url(route_to(...))`, I've left it for the sake of diversity.
- Changed `route_to()` to `url_to()` also in `tests/Authentication/MagicLinkTest.php` (please check carefully for this one as I'm not too sure about it).
> First PR here, sorry in advance if I missed something. Remarks/advice welcome.
> Fix route_to issue

- docs/quickstart.md
**Hello friends**, we have already presented the definition of actions in this way:
```php
public array $actions = [
'login'    => 'CodeIgniter\Shield\Authentication\Actions\Email2FA',
'register' => 'CodeIgniter\Shield\Authentication\Actions\EmailActivator',
];
```
Or it can be as follows
```php
public array $actions = [
'login'    => \CodeIgniter\Shield\Authentication\Actions\Email2FA::class,
'register' => \CodeIgniter\Shield\Authentication\Actions\EmailActivator::class,
];
```
In any case, correction was needed.
> docs: fix definition actions

- src/Controllers/LoginController.php
> refactor: remove calling route_to()

- src/Views/login.php
- src/Views/magic_link_form.php
- src/Views/magic_link_message.php
- src/Views/register.php
> fix : Bootstrap column on mobile

- docs/authentication.md
- docs/customization.md
- src/Config/Auth.php
- src/Config/AuthSession.php
- src/Config/Registrar.php
- src/Controllers/LoginController.php
- src/Controllers/MagicLinkController.php
- src/Controllers/RegisterController.php
- src/Models/UserModel.php
- tests/Controllers/LoginTest.php
- tests/Controllers/RegisterTest.php
See #260
- change validation rules to `regex_match[/\A[a-zA-Z0-9\.]+\z/]`
- add `Config\AuthSession` and move validation rules to it
- refactor
- fix docs
> fix: username validation rules

- src/Commands/Setup.php
- tests/Commands/Setup/ContentReplacerTest.php
Fixes #295
It is difficult to find the code block with regex, so this is ad hoc solution.
Before:
add the Shield routes after the last `$routes->...` line.
After:
add the Shield routes after the last `$routes->...;` line.
> fix: shield:setup adds routes in wrong location

- src/Controllers/RegisterController.php
- tests/Controllers/RegisterTest.php
Fixes #294
- Prevents a logged in user to register
- A corresponding unit test was added
> Fix: register when logged in

- docs/authorization.md
Hello friends,
Ref #266.
The documents needed to be modified.
> docs: fix the way to use  `syncPermissions()`

- docs/authorization.md
Hello
The methods `getGroups()`,`getPermissions()` ,`hasPermission()`  are useful, and I don't know why they aren't in the documentation.
I think it is useful to have them in the documents.
> docs: add explanation of methods `getGroups()`,`getPermissions()` ,`hasPermission()`

- src/Entities/User.php
- src/Models/LoginModel.php
- tests/Unit/UserTest.php
Add a method to get the previous login record of a user, useful for displaying to the user, the last time the account was accessed.
> Add previousLogin method

- README.md
- composer.json
The current code requires PHP 7.4.3+
> PASSWORD_DEFAULT was int 1; now is string '2y' (in *PHP 7.4.0, 7.4.1, and 7.4.2 it was null*)
https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.password-algorithm-constants
See #313
> fix: PHP version

- src/Models/UserModel.php
Hello,
We don't have `permissions `  column in `users `table.
> fix: remove `permissions` from allowedFields UserModel

- src/Authentication/Authenticators/Session.php
Fixes #335
Fix validator to hashedValidator in token
> fix: Session::refreshRememberMeToken() not update row in database

- src/Entities/User.php
- src/Models/RememberModel.php
- src/Models/UserModel.php
See https://github.com/codeigniter4/shield/pull/331#issuecomment-1202085326
- set property cast `integer` for `User::$id`
```console
$ composer test
> phpunit
PHPUnit 9.5.21 #StandWithUkraine
Runtime:       PHP 8.0.21
Configuration: /Users/kenji/work/codeigniter/codeigniter-shield/phpunit.xml
Random Seed:   1659515574
...............................................................  63 / 218 ( 28%)
............................................................... 126 / 218 ( 57%)
............................................................... 189 / 218 ( 86%)
.............................                                   218 / 218 (100%)
Nexus\PHPUnit\Extension\Tachycardia identified these 30 slow tests:
+--------------------------------------------------------------------------------------- …
```
> fix: MySQL tests

- src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
- src/Entities/Cast/IntBoolCast.php
- src/Entities/Entity.php
- src/Entities/Login.php
- src/Entities/User.php
- src/Entities/UserIdentity.php
- src/Models/CheckQueryReturnTrait.php
- tests/Controllers/LoginTest.php
- tests/Unit/UserModelTest.php
- tests/Unit/UserTest.php
Fixes #328
Fixes #327
- add `IntBoolCast`
- add abstract `Entity` class
- fix migration file
- fix `CheckQueryReturnTrait`
- fix tests
```console
$ composer test
> phpunit
PHPUnit 9.5.21 #StandWithUkraine
Runtime:       PHP 8.0.21
Configuration: /Users/kenji/work/codeigniter/codeigniter-shield/phpunit.xml
Random Seed:   1659672472
...............................................................  63 / 225 ( 28%)
............................................................... 126 / 225 ( 56%)
............................................................... 189 / 225 ( 84%)
....................................                            225 / 225 (100%)
Nexus\PHPUnit\Extension\Tachycardia identified these 30 slow tests:
+-------------------------------------------------------------------------- …
```
> fix: PostgreSQL tests

- composer.json
- Use cache. No cache is slow.
- Make `cs-fix` default. CodeIgniter4 repository does not have `style` command.
> chore: update composer cs-fix command

- src/Authentication/Authenticators/AccessTokens.php
- src/Authentication/Authenticators/Session.php
- src/Controllers/MagicLinkController.php
- src/Models/CheckQueryReturnTrait.php
We don't use `declare(strict_types=1)` yet, so these do not cause errors now.
> refactor: fix incorrect types

- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
Sometimes developers might prefer to just extend the default Auth actions classes instead of creating a new one, and since the creation/generation of tokens is done in the `createIdentity()` methods, it is impossible to use it inside child classes as it is `private`. See:
https://github.com/codeigniter4/shield/blob/44e65eff3043530e21337ffdb2d2f6c991a0e548/src/Authentication/Actions/Email2FA.php#L118
https://github.com/codeigniter4/shield/blob/44e65eff3043530e21337ffdb2d2f6c991a0e548/src/Authentication/Actions/EmailActivator.php#L104
Ref #330
> Change the scope of `createIdentity()` method

- docs/customization.md
- src/Controllers/LoginController.php
- src/Controllers/MagicLinkController.php
- src/Controllers/RegisterController.php
> fix: field name translation in validation errors

- src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
According to the [docs](https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_422.html#others), 
* The method `Forge::createTable()` no longer executes a `CREATE TABLE IF NOT EXISTS`. If table is not found in `$db->tableExists($table)` then `CREATE TABLE` is executed.
* The second parameter `$ifNotExists` of `Forge::_createTable()` is deprecated. It is no longer used and will be removed in a future release.
And since shield has been updated to `^4.2.3`, I think this should be followed.
> Change the second param in Forge's `createTable()` method

- docs/install.md
Hello friends,
CodeIgniter Shield requires Codeigniter v4.2.3 or later.
Do we need a description of the lower version?
> docs: remove unnecessary details of `CI4.1.x`

- src/Filters/TokenAuth.php
- tests/Authentication/AuthTest.php
To jump to the method definition quickly.
Before:
Can't go to `AccessTokens::attempt()`
After:
> refactor: add intermediate variable and specify type in TokenAuth

- src/Authentication/Authenticators/AccessTokens.php
- tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
Fixes #360
Checking token in the same second twice throwed "DataException : There is no data to update."
> fix: AccessTokens throws DataException

- .php-cs-fixer.dist.php
- src/Authentication/Actions/EmailActivator.php
- src/Authentication/Authenticators/Session.php
- src/Commands/Setup.php
- src/Filters/AuthRates.php
- src/Filters/ChainAuth.php
- src/Filters/SessionAuth.php
- src/Filters/TokenAuth.php
- src/Models/UserIdentityModel.php
- src/Models/UserModel.php
- tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
- tests/Controllers/MagicLinkTest.php
- tests/Unit/NothingPersonalValidatorTest.php
- add `void_return` rule for php-cs-fixer
- add missing return types
- add doc comments
> refactor: add return types

- docs/install.md
- src/Commands/Setup.php
- tests/Commands/SetupTest.php
Hello friends,
This PR gives command `shield:setup` the ability to automatically implement the security proposal issued in [SecurityAdvisories](https://github.com/codeigniter4/shield/security/advisories/GHSA-5hm8-vh6r-2cjq).
> feat: update `shield:setup` for Security Setup

- composer.json
When using `nexusphp/cs-config`, the `--using-cache` is default `true` if not provided.
https://github.com/NexusPHP/cs-config/blob/e9092a9ab3a59c982bf0c79c89df36a7b2c0b86e/src/Factory.php#L122
> Remove superfluous `--using-cache` option

- src/Models/CheckQueryReturnTrait.php
Fixes https://github.com/codeigniter4/shield/discussions/381
`redirect()->withInput()` or `withErrors()` saves validation errors in the Session.
And the check of the validation errors in Model (`checkQueryReturn()`),
`$this->validation->getErrors()` returns the errors in the Session. 
**How to Test**
```diff
--- a/app/Config/Filters.php
+++ b/app/Config/Filters.php
@@ -36,6 +36,7 @@ class Filters extends BaseConfig
// 'honeypot',
// 'csrf',
// 'invalidchars',
+            'session' => ['except' => 'login*'],
],
'after' => [
'toolbar',
```
```diff
--- a/app/Controllers/Home.php
+++ b/app/Controllers/Home.php
@@ -2,10 +2,22 @@
namespace App\Controllers;
+use Config\Services;
+
class Home extends BaseController
{
public function index()
{
-        return view('welcome_message');
+ …
```
> fix: redirect()->withInput() causes ValidationException

- src/Authentication/Authenticators/Session.php
- src/Controllers/LoginController.php
- src/Controllers/RegisterController.php
- tests/Controllers/RegisterTest.php
- Fixes #349
- if the user goes to the login page, redirected to the Email Activation page and the code will be sent again
- After registration, when the user do not send activation code and the session expires
- if the user logs in, the Email Activation code will be sent again
> fix: Session auth action checks

- src/Models/UserModel.php
Hello friends,
correctly record the datetime for last_active in case of change `defaultLocale`.
**Before:**
```console
+----+--------------------+--------+----------------+--------+--------------------+--------------------+--------------------+------------+
| id | username           | status | status_message | active | last_active        | created_at         | updated_at         | deleted_at |
+----+--------------------+--------+----------------+--------+--------------------+--------------------+--------------------+------------+
| 1  | pooyaparsadadas... |        |                | 1      | 0000-00-00 00:0... | 2022-08-25 15:3... | 2022-08-25 15:3... |            |
+----+--------------------+--------+----------------+--------+--------------------+--------------------+--------------------+ …
```
> fix: correctly record the datetime for `last_active` 

- src/Filters/AuthRates.php
- src/Filters/ChainAuth.php
- src/Filters/SessionAuth.php
- src/Filters/TokenAuth.php
- tests/Unit/FilterInCliTest.php
All filters do not make sense in CLI.
Fixes the PHPStan error:
```
Error: Call to an undefined method CodeIgniter\HTTP\RequestInterface::getHeaderLine().
------ ----------------------------------------------------- 
Line   src/Filters/TokenAuth.php                            
------ ----------------------------------------------------- 
43     Call to an undefined method                          
CodeIgniter\HTTP\RequestInterface::getHeaderLine().  
------ ----------------------------------------------------- 
```
https://github.com/codeigniter4/shield/runs/8072975213?check_suite_focus=true
> fix: add logic to skip filters if not in HTTP

- src/Entities/AccessToken.php
- src/Entities/UserIdentity.php
- src/Models/LoginModel.php
- src/Models/UserModel.php
Ref #331
- fixes for other databases.
Support:
- OCi8
- MySQLi
- Postgre
- SQLSRV
> feat: support other databases

- .github/workflows/phpunit.yml
- tests/_support/Config/Registrar.php
Probably now Shield works with only ~~MySQL or~~ SQLite3.
> chore: add multiple db platforms in GA workflow PHPUnit

- src/Auth.php
- src/Config/Auth.php
- src/Entities/Entity.php
- src/Entities/User.php
- src/Entities/UserIdentity.php
- src/Models/UserModel.php
- src/Result.php
- fix PHPStan error
```
Error: Offset 'except' on array in isset() always exists and is not nullable.
------ -------------------------------------------------------------- 
Line   src/Auth.php                                                  
------ -------------------------------------------------------------- 
109    Offset 'except' on array in isset() always exists and is not  
nullable.                                                     
------ -------------------------------------------------------------- 
```
- update coding style
Because of:
- Upgrading friendsofphp/php-cs-fixer (v3.10.0 => v3.11.0)
- Upgrading phpstan/phpstan (1.8.2 => 1.8.3)
> refactor: fix PHPStan error

- docs/guides/api-tokens.md
- docs/guides/index.md
- docs/index.md
- src/Filters/TokenAuth.php
- tests/Authentication/Filters/AbstractFilterTest.php
- tests/Authentication/Filters/TokenFilterTest.php
Added the first of a handful of guides stepping through setup and use Access Tokens to handle various situations. This one covers generic API requests. 
Along the way I discovered that the `TokenAuth` filter didn't support checking against a scope, so I updated the filter to handle a single permission added when used as a route filter.
```php
$routes->get('users', 'UserController::list', ['filter' => 'tokens:users-read']);
```
> ApiToken docs and filter update.

- docs/guides/api-tokens.md
Missing apostrophe in getVar() method parameter
```php
$routes->get('/access/token', static function() {
$token = auth()->user()->generateAccessToken(service('request')->getVar('token_name));
return json_encode(['token' => $token->raw_token]);
});
```
> docs: Missing apostrophe

- docs/install.md
Hello friends.
We have answered how to protect routes by several users in several discussions.
However, I recently received a similar message about how to protect the site panel.
I have covered this topic in this PR.
> docs: explanation of how to use the `session` filter to protect pages

- docs/install.md
ref: https://github.com/codeigniter4/shield/discussions/441#discussioncomment-3672007
It seems that in https://github.com/codeigniter4/shield/pull/429#issuecomment-1242676793 I meant to _rewrite_ filter `session`, but I didn't, that was my carelessness, sorry.
> docs: fix protect all url with `$globals`

- docs/concepts.md
See https://github.com/codeigniter4/shield/pull/439#discussion_r974787536 and https://github.com/codeigniter4/shield/issues/438
> docs: add note about strong_password

- src/Entities/User.php
- src/Entities/UserIdentity.php
- src/Models/UserIdentityModel.php
- src/Models/UserModel.php
- tests/Unit/UserModelTest.php
- tests/Unit/UserTest.php
Fixes #450
- Fix bug that when `UserIdentity` is changed (including when saving User object), the correct user identities does not be returned afterwards.
- Now `UserModel` does not alter the passed `User` object state when saving, ~~but when it is an insertion, add the user id to it.~~
> fix: bug that when UserIdentity is changed, the correct user identities are not returned afterwards

- src/Views/magic_link_message.php
Removed unnecessary ending form tag from `magic_link_message.php`
> bug: fix magic_link_message view template

- src/Entities/AccessToken.php
- src/Entities/UserIdentity.php
see https://github.com/codeigniter4/shield/actions/runs/3182827194/jobs/5189273566
```
Error: Property CodeIgniter\Shield\Entities\AccessToken::$last_used_at (CodeIgniter\I18n\Time|null) does not accept string.
Error: Property CodeIgniter\Shield\Entities\UserIdentity::$last_used_at (CodeIgniter\I18n\Time|null) does not accept string.
------ ----------------------------------------------------------------- 
Line   src/Authentication/Authenticators/AccessTokens.php               
------ ----------------------------------------------------------------- 
131    Property CodeIgniter\Shield\Entities\AccessToken::$last_used_at  
(CodeIgniter\I18n\Time|null) does not accept string.             
------ ----------------------------------------------------------------- 
------ …
```
> docs: add `string` property for `$last_used_at`

- .github/workflows/deptrac.yml
```
Box Requirements Checker
========================
> Using PHP 8.0.25
> PHP is using the following php.ini file:
/etc/php/8.0/cli/php.ini
> Checking Box requirements:
E...
Error: ] Your system is not ready to run the application.                       
Fix the following mandatory requirements:
=========================================
* The application requires the version "^8.1" or greater.
Error: Process completed with exit code 1.
```
https://github.com/codeigniter4/shield/actions/runs/3374291576/jobs/5599760846
> chore: update GA deptrac.yml

- src/Config/Auth.php
- src/Controllers/RegisterController.php
- tests/Controllers/LoginTest.php
The default configuration does not support `username` as login id.
There is no form input for `username`, and no validation rules for it.
But Shield accepts `username` in the login form (attackers can send any field), 
and sends it to the database without validation.
This is not an exploitable vulnerability, but it is undesirable. Unvalidated user input should not be sent to the database.
> fix: remove `username` in $validFields by default

- src/Authorization/Traits/Authorizable.php
- tests/Authorization/AuthorizableTest.php
Fixes #505
- improve the error message
> fix: TypeError when checking invalid permission

- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Controllers/MagicLinkController.php
- src/Language/de/Auth.php
- src/Language/en/Auth.php
- src/Language/es/Auth.php
- src/Language/fa/Auth.php
- src/Language/fr/Auth.php
- src/Language/id/Auth.php
- src/Language/ja/Auth.php
- src/Language/sk/Auth.php
- src/Views/Email/email_2fa_email.php
- src/Views/Email/email_activate_email.php
- src/Views/Email/magic_link_email.php
- tests/Controllers/ActionsTest.php
It is common practice to include in email verification emails some user request info like `IP Address`, `User Agent Device` & `Date` when a user is asked for some code. This PR adds this information.
I also improved default email templates to improve readability of the `code`.  
@lonnieezell  @kenjis  @MGatner I don't know if we want to provide more complex Email templates, or if basic HTML is fine for the start of using this library and leave it completely to the developer.
Language files are not completed, some translated with Google Translator. 
Please help with translations. 
Here is what it looks like now in the Email client.
> feat: add request info to all emails

- src/Models/UserModel.php
- tests/Unit/UserTest.php
> fix: withIdentities() when user not exists

- README.md
- composer.json
- docs/install.md
See #516
It requires v4.2.6, but it has the Security Advisory: https://github.com/codeigniter4/CodeIgniter4/security/advisories/GHSA-745p-r637-7vvp
> chore: update minimum CI4 version to 4.2.7

- README.md
- docs/install.md
Hello,
PR are created to improve the display of the code block on the site and to facilitate the copying of commands by the user.
see : https://github.com/codeigniter4/shield/pull/508#issuecomment-1305485529
see : https://codeigniterchat.slack.com/archives/C47DHAS7M/p1668107201982039?thread_ts=1668040926.000199&cid=C47DHAS7M
> docs: add code block language for fix website

- src/Config/Auth.php
- update comments
- update the default values
```php
<?php
echo PASSWORD_ARGON2_DEFAULT_MEMORY_COST . PHP_EOL;
echo PASSWORD_ARGON2_DEFAULT_TIME_COST . PHP_EOL;
echo PASSWORD_ARGON2_DEFAULT_THREADS . PHP_EOL;
```
```console
$ php test.php 
65536
4
1
```
```console
$ php -v
PHP 8.1.12 (cli) (built: Oct 30 2022 12:55:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
with Xdebug v3.1.5, Copyright (c) 2002-2022, by Derick Rethans
with Zend OPcache v8.1.12, Copyright (c), by Zend Technologies
```
> config: update ARGON2I/ARGON2ID Algorithm options

- docs/concepts.md
`Config\Auth->userProvider` → `Config\Auth::$userProvider`
> docs: fix property notation

- src/Authentication/Passwords/CompositionValidator.php
- tests/Unit/CompositionValidatorTest.php
In the current implementation, `$minimumPasswordLength` means bytes, not characters.
> fix: minimum password length check

- tests/Language/AbstractTranslationTestCase.php
```console 
------ ----------------------------------------------------------------------- 
Line   tests/Language/ItalianTranslationTest.php                              
------ ----------------------------------------------------------------------- 
12     Property                                                               
Tests\Language\ItalianTranslationTest::$excludedLocaleKeyTranslations  
(array<string, string>) does not accept default value of type          
array<int, string>.                                                    
------ ----------------------------------------------------------------------- 
```
https://github.com/codeigniter4/shield/actions/runs/3497594223/jobs/5856927086
> docs: fix phpdocs for `PHPStan` analyze

- docs/auth_actions.md
- docs/concepts.md
- docs/quickstart.md
- src/Config/Auth.php
To fix psalm issues.
See  #539
Before:
```console
INFO: PropertyTypeCoercion - src/Config/Auth.php:211:40 - $this->passwordValidators expects 'array<array-key, class-string<CodeIgniter\Shield\Authentication\Passwords\ValidatorInterface>>',  parent type 'array{"CodeIgniter\\Shield\\Authentication\\Passwords\\CompositionValidator", "CodeIgniter\\Shield\\Authentication\\Passwords\\NothingPersonalValidator", "CodeIgniter\\Shield\\Authentication\\Passwords\\DictionaryValidator"}' provided (see https://psalm.dev/198)
public array $passwordValidators = [
'CodeIgniter\Shield\Authentication\Passwords\CompositionValidator',
'CodeIgniter\Shield\Authentication\Passwords\NothingPersonalValidator',
'CodeIgniter\Shield\Authentication\Passwords\DictionaryValidator',
// …
```
> refactor: use `::class` constants

- src/Models/UserModel.php
- tests/Unit/UserModelTest.php
Fixes  #546
This is a case that `empty()` causes a bug.
> fix: findByCredentials() returns User when email is empty string

- .github/workflows/rector.yml
- .php-cs-fixer.dist.php
- rector.php
- tests/Authentication/AuthenticationTest.php
- tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
- tests/Authentication/Authenticators/SessionAuthenticatorTest.php
- tests/Authentication/Filters/AbstractFilterTest.php
- tests/Authentication/HasAccessTokensTest.php
- tests/Authorization/AuthorizableTest.php
- tests/Language/AbstractTranslationTestCase.php
- tests/Unit/CompositionValidatorTest.php
- tests/Unit/DictionaryValidatorTest.php
- tests/Unit/FilterInCliTest.php
- tests/Unit/NothingPersonalValidatorTest.php
- tests/Unit/PwnedValidatorTest.php
- add `declare(strict_types=1)` in `rector.php`
- update rector version to `^0.15.1`
- add rector rules
- remove deprecated `TypedPropertyRector`
- refactor test code by rector
- update `.php-cs-fixer.dist.php`
```
PHP Fatal error:  Uncaught _PHPStan_9a6ded56a\Nette\Schema\ValidationException: Unexpected item 'parameters › deprecationRulesInstalled'. in phar:///home/runner/.composer/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/schema/src/Schema/Processor.php:75
Fatal error: Uncaught _PHPStan_9a6ded56a\Nette\Schema\ValidationException: Unexpected item 'parameters › deprecationRulesInstalled'. in phar:///home/runner/.composer/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/schema/src/Schema/Processor.php:75
Stack trace:
Stack trace:
#0 …
```
> chore: update rector.php

- docs/customization.md
- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Controllers/LoginController.php
- src/Controllers/MagicLinkController.php
- src/Controllers/RegisterController.php
- src/Traits/Viewable.php
Fixes  #555
When using a theme/template system other than the built in CI features, it is very difficult to integrate without copying large amounts of logic from Actions and controllers that a developer should not have to maintain. 
This adds a new trait, `Viewable`, that provides a simple, consistent way to override just how views are rendered.
> dev: Allow easier overriding of views in developer applications.

- docs/install.md
- docs/quickstart.md
> docs: add configuration for Config\Email

- docs/concepts.md
- src/Commands/Generators/UserModelGenerator.php
- src/Commands/Generators/Views/usermodel.tpl.php
- src/Config/Registrar.php
- tests/Commands/UserModelGeneratorTest.php
> feat: add `shield:model` command

- src/Controllers/LoginController.php
I have declared the following under my `Auth.php` file:
```php
public function logoutRedirect(): string
{
$url = auth()->user()->inGroup('admin')
? 'login'
: setting('Auth.redirects')['logout'];
return $this->getUrl($url);
}
```
And get a **Call to a member function inGroup() on null** error when navigating to `/logout`.
After some debugging I realized the logout action function under `LoginController.php` logs the user out before redirecting, causing the `redirect()` helper to get an invalid value.
To overcome this, I first capture the URL in a variable and pass it to the redirect function after the auth is logged out:
```php
public function logoutAction(): RedirectResponse
{
$url = config('Auth')->logoutRedirect();
auth()->logout();
return redirect()->to($url)->with('message', …
```
> bug: Call to a member function inGroup() on null after logging out

- composer.json
Codeigniter considers `ext-curl` optional. On the other hand, `PwnedValidator::class` uses  `Services::curlrequest` to connect with API. Therefore, it is better to inform about this matter.
> chore: add `ext-curl` to suggest if use `PwnedValidator::class`

- docs/customization.md
- docs/install.md
- src/Config/Auth.php
- src/Config/AuthRoutes.php
In situations when a developer decides to put the routes in a group like so:
```php
$routes->group('accounts', static function($routes) {
service('auth')->routes($routes);
});
```
Calls to `route_to('login')` and `route_to('register')` will return an error because there isn't any named route for that.
By explicitly setting named routes for each of the auth routes, the routing works well whether in groups or not.
> Fix: Unnamed Auth routes returns an error when inside a route group

- src/Commands/Setup.php
- tests/Commands/SetupTest.php
See #596
In version CI 4.3.0+, is used (`string`), 
https://github.com/codeigniter4/CodeIgniter4/blob/758889a19d53d155e62b7d1edb49498e395acf2e/app/Config/Security.php#L13-L19
which makes `setSecurityCSRF()` function not work properly.
> fix: update `shield:setup` for correct run in CI4.3.0+

- phpstan.neon.dist
- rector.php
- src/Commands/Generators/UserModelGenerator.php
- tests/Commands/UserModelGeneratorTest.php
See #596
- update UserModelGenerator::run()
- update tests
> Update UserModelGenerator for CI 4.3.0

- psalm-baseline.xml
- psalm.xml
- psalm_autoload.php
- rector.php
- tests/Commands/SetupTest.php
- tests/Controllers/LoginTest.php
- tests/Unit/UserModelTest.php
~~Needs #595~~
See #596
- update tests
- add psalm baseline
> Update failed tests for CI4.3.0

- src/Filters/AbstractAuthFilter.php
- tests/Authentication/Filters/GroupFilterTest.php
- tests/Authentication/Filters/PermissionFilterTest.php
Steps to reproduce:
1. Create an admin group _(if you don't already have one)_
2. Register a new user and add to the group
3. Create two views that can only be accessible by this group, let's call them A and B
4. Filter these views _(via the route or filter)_
5. Login and visit page A.
6. Change the group of the logged in user, preferrably from the database directly
7. Try to visit page B.
What you'll notice is that the browser dies of too many redirects error.  This happens because the filter is redirecting the user back to the previous page, which at this point, the user no longer has enough privileges to access it.
A real-life scenario:
A forum website with multiple groups and permissions, an admin might decide to remove a certain permission from a user or remove the user from a …
> Fix: groups and permissions filter redirects

- docs/customization.md
- docs/quickstart.md
- distinguish between *Configure* and *Customize*, moving *Configure* to `quickstart.md` and *Customize* to `customization.md`
> docs: improve quickstart.md and customization.md

- docs/concepts.md
- docs/customization.md
- move *how to customize User Provider* to customization.md
> docs: improve User Provider

- docs/authorization.md
See https://github.com/codeigniter4/shield/discussions/600#discussioncomment-4691901
- [$filters](https://codeigniter.com/user_guide/incoming/filters.html#filters) cannot set filer arguments.
> docs: remove unsupported Filter code sample

- docs/forcing_password_reset.md
- docs/index.md
- docs/install.md
- docs/quickstart.md
- src/Config/Auth.php
- src/Config/Registrar.php
- src/Entities/User.php
- src/Filters/ForcePasswordResetFilter.php
- src/Models/UserIdentityModel.php
- src/Models/UserModel.php
- src/Traits/Resettable.php
- tests/Authentication/ForcePasswordResetTest.php
- tests/Unit/UserIdentityModelTest.php
Fixes #522 
Implemented the force password reset functionality with the following highlights:
- Added a new `Resettable` trait that is used on the `User` entity. This provides a couple of methods to check if a user requires a password reset or not, forcing a password reset and undoing the forced password reset. Thanks @lonnieezell 
- Updated the `UserIdentityModel` with methods to force a password reset for multiple users and globally, i.e., all the users.
- Added a filter `ForcePasswordResetFilter` to check and redirect appropriately after a user is logged in.
- Updated the `Registrar` config.
- Updated `Auth` config to allow devs to specify a `force_reset` redirect.
- Updated `quickstart.md` and `install.md` docs.
- And of course, created and updated tests.
> Feat: Force password reset

- rector.php
- src/Language/de/Auth.php
- src/Language/en/Auth.php
- src/Language/es/Auth.php
- src/Language/fa/Auth.php
- src/Language/fr/Auth.php
- src/Language/id/Auth.php
- src/Language/it/Auth.php
- src/Language/ja/Auth.php
- src/Language/sk/Auth.php
- src/Language/tr/Auth.php
CI4 is built for PHP 7.4+, and everything in the framework is namespaced,
except for the helper and lang files.
see https://github.com/codeigniter4/CodeIgniter4/pull/7210
> refactor: remove `namespace` from language files

- src/Models/LoginModel.php
- src/Models/TokenLoginModel.php
- src/Models/UserIdentityModel.php
- src/Models/UserModel.php
E.g. ErrorException: Since fakerphp/faker 1.14: Accessing property "userName" is deprecated, use "userName()" instead.
Try:
```
$ CODEIGNITER_SCREAM_DEPRECATIONS=true composer test
```
> refactor: replace deprecated Faker property access

- docs/authentication.md
- docs/authorization.md
- src/Auth.php
- src/Authentication/Actions/EmailActivator.php
- src/Authentication/Authenticators/Session.php
- src/Controllers/RegisterController.php
- src/Entities/User.php
- src/Filters/SessionAuth.php
- src/Filters/TokenAuth.php
- src/Language/de/Auth.php
- src/Language/en/Auth.php
- src/Language/es/Auth.php
- src/Language/fa/Auth.php
- src/Language/fr/Auth.php
- src/Language/id/Auth.php
- src/Language/it/Auth.php
- src/Language/ja/Auth.php
- src/Language/pt-BR/Auth.php
- src/Language/sk/Auth.php
- src/Language/tr/Auth.php
- src/Traits/Activatable.php
- tests/Authentication/Filters/SessionFilterTest.php
- tests/Authentication/Filters/TokenFilterTest.php
- tests/Unit/UserTest.php
Fixes #459
Previously, the `active` column for the user was not being used except that the `EmailActivator` flow would set it. This PR addresses this by: 
- Adding a new `Activatable` trait that is used on the `User` entity.  This provides methods to check if a user is activated or not, and utility methods to activate/deactivate that user.
- The `SessionAuth` and `TokenAuth` filters are updated to check the user's active status and redirect to login/return a 403 status code, respectively, when they aren't active. This takes into account if no activator is required after registration.
> feat: User activation checks and utility functions.

- src/Traits/Activatable.php
Follow-up #580
`UserModel::update()` returns only true.
So returning the value and checking the return value is meaningless.
> refactor: change return type to void

- docs/customization.md
- src/Authentication/Authenticators/Session.php
- tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Closes #334
Previously, only `email` and `username` were actually working as valid fields to login with. This was not the original intention. 
This changes this to ensure that any field listed within `$validFields` that is within the `users` table can be used as a valid login credential for the Session authenticator. All login attempts must still have a password associated.
> fix: Custom login fields should work for logging in.

- docs/install.md
A user must be able to log out if they opt out of changing their password.
> docs: add `logout` for `force-reset` except

- src/Language/pt-BR/Auth.php
Supersedes #672 
Added portuguese (pt-BR) translations
> lang: translate pt-BR strings

- src/Auth.php
- src/Collectors/Auth.php
- tests/Collectors/AuthTest.php
From now on, we know that before releasing the new version, we have to send PR **Prep for Beta X**, which includes the shield version update and other contributors' commits.
Also, troubleshooting and communication with users will be better.
Note: I have changed **Auth** to **Shield**.
**This PR should be merged before the new version is released.**
> feat: add shield version for Increase improvement

- .github/workflows/docs.yml
See https://github.com/codeigniter4/shield/actions/runs/4454434810/jobs/7823617312
```
Run mkdocs gh-deploy --force
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/runner/work/shield/shield/site
INFO     -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
- banning_users.md
- forcing_password_reset.md
INFO     -  Documentation built in 0.46 seconds
WARNING  -  Version check skipped: No version specified in previous deployment.
INFO     -  Copying '/home/runner/work/shield/shield/site' to 'gh-pages' branch and pushing to GitHub.
remote: Permission to codeigniter4/shield.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/codeigniter4/shield/': The requested URL returned …
```
> chore: fix workflow docs.yml

- docs/authentication.md
- docs/quickstart.md
If a dev customizes the UserModel and changes the model name, the sample code dose not work.
> docs: add and use auth()->getProvider()

- src/Controllers/LoginController.php
- src/Controllers/MagicLinkController.php
- src/Controllers/RegisterController.php
With the current data validation checks in the controllers, an empty POST request with valid GET parameters will cause the validation to pass. Since this data is always later fetched from the POST request body, it will be null and errors will be thrown.
> fix: only validate data from POST request body

- docs/guides/mobile_apps.md
Fix validation check to only validate POST request body.
Issue related to #695
> docs: use `validateData()` instead of `validate()`

- docs/guides/mobile_apps.md
1. Currently, the documentation on mobile apps does not include the password field for logging in, which makes the request to fail. This PR adds the complete credentials for logging in, as seen below:
https://github.com/codeigniter4/shield/blob/799c6477504dac7dc0dc45e2e9c1d8a063e23ca8/src/Controllers/LoginController.php#L54-L56
2. The `device_name` POST request is required to generate the access token, so, it is supposed to be included in the validation rules. Not passing it returns this error:
```
Argument 1 passed to CodeIgniter\\Shield\\Entities\\User::generateAccessToken() must be of the type string, null given
```
> docs: update guides/mobile_apps.md

- docs/addons/jwt.md
> docs: fix jwt.md

- docs/guides/mobile_apps.md
There is no need to change the status code since a validation error is still an authentication failure. 
See https://github.com/codeigniter4/shield/pull/195#discussion_r1173193039
> [15.5.21. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.21)[422 Unprocessable Content](https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content)
>
> The 422 (Unprocessable Content) status code indicates that the server understands the content type of the request content (hence a [415 (Unsupported Media Type)](https://www.rfc-editor.org/rfc/rfc9110.html#status.415) status code is inappropriate), and the syntax of the request content is correct, but it was unable to process the contained instructions. For example, this status code can be sent if an XML request content contains …
> docs: change the status code from 422 to 401

- bin/update-en-comments
- src/Language/ja/Auth.php
- add script to update en comments
- translate JWT Exceptions
> lang: update ja

- docs/authorization.md
- src/Config/AuthGroups.php
See https://forum.codeigniter.com/showthread.php?tid=87457
- add description for user-level and group-level permissions
- update the comments in `Config\AuthGroups`.
> docs: improve descriptions on permissions

- src/Authentication/Passwords.php
- src/Controllers/LoginController.php
- src/Controllers/RegisterController.php
The getMaxLenghtRule() method name has a typo and should be renamed to getMaxLengthRule() in 3 source files.
> fix: typo in `getMaxLengthRule()` method name

- src/Authentication/Passwords/NothingPersonalValidator.php
- tests/Controllers/RegisterTest.php
- tests/Unit/NothingPersonalValidatorTest.php
**superseded:** #712 
Sorry for my previous pull request. I closed it because after applying the gpg addition, conflicts occurred in the code for earlier commits. 
after that
> git rebase -i --root --exec 'git commit --amend --no-edit --no-verify -S'
And I thought it would be easier to create a new pull request than to resolve these conflicts. 
I also added some tests (integration and unit) that describe the issue I faced.
If you don't apply the changes I made, I will get an error in the tests. 
```
There was 1 error:
1) Tests\Controllers\RegisterTest::testRegisterActionWithBadEmailValue
ErrorException: Undefined offset: 1
\PhpstormProjects\shield\src\Authentication\Passwords\NothingPersonalValidator.php:78
\PhpstormProjects\shield\src\Authentication\Passwords\NothingPersonalValidator.php: …
```
> fix: nothing personal validator error with bad email value

- src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
> feat: Add InnoDB engine to migration create table methods

- docs/guides/strengthen_password.md
- src/Authentication/Passwords/ValidationRules.php
- src/Controllers/RegisterController.php
Previously, the `ValidationRules::buildUserFromRequest()` only checks for `POST`ed requests.
With this PR, it can now check for any type of request including json requests. 
Fixes #612
> fix: add support for all request types when building a user from request.

- admin/pre-commit
See: https://github.com/codeigniter4/CodeIgniter4/pull/7618
> chore: remove php-stan from the precommit hook

- src/Auth.php
- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Authentication/Authenticators/AccessTokens.php
- src/Authentication/Authenticators/Session.php
- src/Authentication/Passwords.php
- src/Authentication/Passwords/ValidationRules.php
- src/Authorization/Traits/Authorizable.php
- src/Config/Services.php
- src/Controllers/LoginController.php
- src/Controllers/MagicLinkController.php
- src/Controllers/RegisterController.php
- src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
- src/Filters/ChainAuth.php
- src/Filters/ForcePasswordResetFilter.php
- src/Filters/SessionAuth.php
- src/Views/email_2fa_show.php
- src/Views/email_2fa_verify.php
- src/Views/email_activate_show.php
- src/Views/login.php
- src/Views/magic_link_form.php
- src/Views/magic_link_message.php
- src/Views/register.php
Fixes #761
Reverts codeigniter4/shield#748
> Revert "refactor: use ::class keyword in config()"

- .github/workflows/no-merge-commits.yml
https://github.com/marketplace/actions/no-merge-commits-action
> chore: add no-merge-commits.yml

- tests/Unit/FilterInCliTest.php
- tests/Unit/NothingPersonalValidatorTest.php
> chore: fix coding style error

- docs/authorization.md
- src/Authorization/Traits/Authorizable.php
- tests/Authorization/AuthorizableTest.php
Added support for multiple permissions check for users via the `Authorizable` trait.
With this pull request, instead of writing:
```php
if ($user->can('user.create') || $user->can('user.edit')){
//
}
```
we use this:
```php
if ($user->can('user.create', 'user.edit')){
//
}
```
> feat: add support for multiple permissions check for users

- src/Authentication/Authenticators/JWT.php
- src/Authentication/JWT/Adapters/FirebaseAdapter.php
- src/Authentication/JWT/JWSEncoder.php
- src/Filters/JWTAuth.php
- src/Models/BaseModel.php
Follow-up #762
If FQCN is specified, devs cannot override.
> fix: use short classname for config()

- tests/Authentication/Authenticators/JWTAuthenticatorTest.php
- tests/Authentication/Filters/JWTFilterTest.php
- tests/Unit/Authentication/JWT/Adapters/FirebaseAdapaterTest.php
- tests/Unit/Authentication/JWT/JWTManagerTest.php
Follow-up #796
Ref #802
This PR fixes the following test error with CI v4.4.0:
```
1) Tests\Unit\Authentication\JWT\JWTManagerTest::testParseCanSpecifyKey
ErrorException: Undefined array key "mobile"
/home/runner/work/shield/shield/src/Authentication/JWT/Adapters/FirebaseAdapter.php:145
/home/runner/work/shield/shield/src/Authentication/JWT/Adapters/FirebaseAdapter.php:112
/home/runner/work/shield/shield/src/Authentication/JWT/JWSEncoder.php:62
/home/runner/work/shield/shield/src/Authentication/JWTManager.php:[73](https://github.com/codeigniter4/shield/actions/runs/5984579479/job/16235976345?pr=801#step:11:74)
/home/runner/work/shield/shield/tests/Unit/Authentication/JWT/JWTManagerTest.php:311
```
> test: use short classname for `config()`

- src/Language/ar/Auth.php
- src/Language/bg/Auth.php
- src/Language/de/Auth.php
- src/Language/en/Auth.php
- src/Language/es/Auth.php
- src/Language/fa/Auth.php
- src/Language/fr/Auth.php
- src/Language/id/Auth.php
- src/Language/it/Auth.php
- src/Language/ja/Auth.php
- src/Language/lt/Auth.php
- src/Language/pt-BR/Auth.php
- src/Language/pt/Auth.php
- src/Language/sk/Auth.php
- src/Language/sr/Auth.php
- src/Language/sv-SE/Auth.php
- src/Language/tr/Auth.php
- src/Language/uk/Auth.php
- src/Views/email_activate_show.php
- src/Views/login.php
- src/Views/magic_link_form.php
- src/Views/register.php
Currently, when filling forms, there is no indication of the field being filled _(or what is expected of the user)_ after a user has entered value in the input fields. If a user forgets what was in the placeholder before filling the form, s/he will need to delete the entire entry in the input to know what the field expects. See screenshot below:
This PR improves user experience by providing a floating label to indicate the field that is being filled. See screenshot below:
> feat: improve user experience in forms

- phpstan.neon.dist
- src/Entities/User.php
- src/Models/UserModel.php
- tests/Unit/UserTest.php
In the `UserModel` - when we use `withIdentities()` method the query is produced properly. 
The problem occurs in the `assignIdentities()` method, when we're trying to assign identities to the users.
We're working with the `User` entity, and there is a line: 
```
$newIdentities   = $mappedUsers[$userId]->identities;
```
It will call `getIdentities()` method which will produce a query to the DB, since there are no identities assigned yet.
This PR solves this problem.
> fix: UserModel::assignIdentities() always produces a DB query

- src/Filters/AbstractAuthFilter.php
- tests/Authentication/Filters/GroupFilterTest.php
- tests/Authentication/Filters/PermissionFilterTest.php
> fix: unauthorized users for groups and permissions are not redirected to the previous url

- composer.json
- phpstan-baseline.php
- phpstan.neon.dist
- rector.php
- add phpstan-strict-rules
- enable rules
- disallowedLooseComparison: true
- booleansInConditions: true 
- disallowedConstructs: true
- matchingInheritedMethodNames: true
- update baseline
Ref https://github.com/codeigniter4/CodeIgniter4/pull/7916
**Checklist:**
> chore: add phpstan-strict-rules

- src/Authentication/Passwords/ValidationRules.php
- tests/Controllers/RegisterTest.php
> fix: cannot register when you remove email from `$validFields`

- composer.json
- phpstan-baseline.php
v1.3.0.70400 offers shiny new features
```
* Provides precise return types for `CodeIgniter\Model`'s `find()`, `findAll()`, and `first()` methods.
* Allows dynamic return type transformation of `CodeIgniter\Model` when `asArray()` or `asObject()` is called.
```
The new errors added is the result of phpstan not able to infer when names of selected fields are renamed, e.g. `select('secret1 as email')`
**Checklist:**
> chore: update phpstan-codeigniter to v1.3

- src/Authentication/Authenticators/HmacSha256.php
> fix: [HMAC Auth] wrong header key

- rector.php
- src/Commands/Exceptions/BadInputException.php
- src/Commands/Exceptions/CancelException.php
- src/Commands/User.php
- src/Commands/Utils/InputOutput.php
- src/Controllers/RegisterController.php
- src/Exceptions/UserNotFoundException.php
- src/Test/MockInputOutput.php
- src/Validation/RegistrationValidationRules.php
- tests/Commands/UserTest.php
- tests/Commands/Utils/MockInputOutput.php
Supersedes #579
Closes #566
Add command `shield:user` to manage users:
```
shield:user create -n newusername -e newuser@example.com
```
```
shield:user activate -n username
shield:user activate -e user@example.com
```
```
shield:user deactivate -n username
shield:user deactivate -e user@example.com
```
```
shield:user changename -n username --new-name newusername
shield:user changename -e user@example.com --new-name newusername
```
```
shield:user changeemail -n username --new-email newuseremail@example.com
shield:user changeemail -e user@example.com --new-email newuseremail@example.com
```
```
shield:user delete -i 123
shield:user delete -n username
shield:user delete -e user@example.com
```
```
shield:user password -n username
shield:user password -e user@example.com
``` …
> feat: add CLI command to manage users

- UPGRADING.md
- src/Authentication/Authenticators/AccessTokens.php
- src/Config/AuthToken.php
- src/Filters/TokenAuth.php
- tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
> fix: AccessTokens authenticator records all accesses to database

- src/Commands/User.php
Follow-up #833
In previous versions, we used `strong_password` not `strong_password[]`.
**Checklist:**
> fix: remove `strong_password` from shield:user validation rules

- docs/guides/api_tokens.md
- docs/references/authentication/tokens.md
- src/Authentication/Traits/HasAccessTokens.php
- src/Models/UserIdentityModel.php
- tests/Authentication/HasAccessTokensTest.php
After losing some tokens while i developed my app and i didnt want to remove all of the tokens i changed the `revokeAccessToken` to support removeing them by the secret that you can get with the `AccessTokens()` function.
superseded: #838 
**Checklist:**
> feat: added `revokeAccessTokenBySecret()`

- .github/workflows/docs.yml
- docs/addons/jwt.md
- docs/assets/css/dark_mode.css
- docs/assets/js/curl.min.js
- docs/customization/login_identifier.md
- docs/customization/table_names.md
- docs/customization/validation_rules.md
- docs/getting_started/concepts.md
- docs/getting_started/install.md
- docs/guides/api_hmac_keys.md
- docs/guides/api_tokens.md
- docs/guides/mobile_apps.md
- docs/guides/strengthen_password.md
- docs/quick_start_guide/using_authorization.md
- docs/quick_start_guide/using_session_auth.md
- docs/references/authentication/authentication.md
- docs/references/authentication/hmac.md
- docs/references/authorization.md
- docs/references/controller_filters.md
- docs/references/magic_link_login.md
- docs/user_management/managing_users.md
- mkdocs.yml
https://datamweb.github.io/shield
See https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
You need `pip3 install mkdocs-git-revision-date-localized-plugin`.
**Checklist:**
> Improve site part2

- docs/addons/jwt.md
See https://github.com/codeigniter4/shield/pull/860#discussion_r1340639476
highlight.js does not support dotenv.
**Checklist:**
> docs: change dotenv to text

- admin/how_to_build_docs.md
- add "How to Build Shield Documentation"
**Checklist:**
> docs: add "How to Build Shield Documentation"

- docs/customization/validation_rules.md
- src/Commands/User.php
- src/Config/Auth.php
- src/Controllers/LoginController.php
- src/Controllers/MagicLinkController.php
- src/Controllers/RegisterController.php
- src/Validation/RegistrationValidationRules.php
- src/Validation/ValidationRules.php
- put validation rules into the `ValidationRules` class
- make password rules reusable
**Checklist:**
> refactor: validation rules

- src/Validation/ValidationRules.php
Currently, the `Validation` class declares the properties `$config` and `$tables` as private which makes them impossible to use within child classes. This PR fixes that.
**Checklist:**
> fix: Change the visibility of validation properties for easier inheritance

- docs/getting_started/install.md
It is not recommended. Because it should be set to `session` in all environments.
**Checklist:**
> docs: remove `Config\Security::$csrfProtection` config method by `.env`

- composer.json
- src/Authentication/Actions/Email2FA.php
- src/Authentication/Actions/EmailActivator.php
- src/Controllers/MagicLinkController.php
See https://forum.codeigniter.com/showthread.php?tid=88545
The Email helper is used in a limited number of places, and it would be inefficient to load it on every page.
Also, if a library autoloads helpers by Composer, there is no way to stop that loading. 
So I have changed my mind, it is better not using helper autoloading by Composer in libraries.
If autoloading is necessary, developers can set it up in `Config\Autoload`.
**Checklist:**
> refactor: remove Composer autoloading of email helper

- README.md
- UPGRADING.md
- composer.json
- docs/getting_started/install.md
- src/Test/MockInputOutput.php
- tests/Commands/SetupTest.php
- tests/Commands/UserModelGeneratorTest.php
- tests/Controllers/LoginTest.php
CI 4.4 is already released, and there are vulnerabilities in prior to 4.3.5. 
- update minimum CI4 version to 4.3.5
- remove code for CI 4.2.x or before
**Checklist:**
> refactor: update minimum CI4 version to 4.3.5

- .github/workflows/docs.yml
- admin/how_to_build_docs.md
- mkdocs.yml
Follow-up #839
- add [mkdocs-redirects](https://github.com/mkdocs/mkdocs-redirects) plugin
- configure page redirects
**Checklist:**
> mkdocs: configure page redirects

- docs/index.md
- add features
- add emojis to section titles
**Checklist:**
> docs: improve home

- src/Commands/Generators/UserModelGenerator.php
- src/Models/CheckQueryReturnTrait.php
> refactor: remove outdated code for CI 4.2 or before

- docs/getting_started/install.md
- rector.php
- src/Commands/BaseCommand.php
- src/Commands/Setup.php
- src/Commands/User.php
- src/Commands/Utils/InputOutput.php
- src/Test/MockInputOutput.php
- tests/Commands/SetupTest.php
~~Needs #871~~
- `shield:setup` does Email setup
- refactor
**Checklist:**
> feat: `shield:setup` does Email setup

- src/Controllers/RegisterController.php
- src/Views/email_activate_show.php
- Used named route for redirect in the **src/Controllers/RegisterController.php** file
- Used named route for form action in **src/Views/email_action_show.php** file.
Fixes #879 
**Checklist:**
> fix: use named routes for redirects and form submission

- docs/customization/route_config.md
See https://github.com/codeigniter4/shield/pull/883#issuecomment-1752194788
**Checklist:**
> docs: add how to use locale routes

- admin/RELEASE.md
- small improvements
**Checklist:**
> docs: update RELEASE.md

- rector.php
- src/Authentication/Passwords/NothingPersonalValidator.php
- src/Authentication/Passwords/PwnedValidator.php
Enable `StringifyStrNeedlesRector` with set `@return array<int, string>` to `strip_explode()` method and run Rector to apply `ArraySpreadInsteadOfArrayMergeRector` as same type.
**Checklist:**
> [Rector] Apply StringifyStrNeedlesRector

- docs/customization/login_identifier.md
Improve the instructions.
**Checklist:**
> docs: improve instructions for Customizing Login Identifier

- docs/customization/login_identifier.md
Follow-up #895
- trivial fixes
**Checklist:**
> docs: small fixes for Customizing Login Identifier

- src/Views/email_2fa_show.php
- src/Views/email_2fa_verify.php
- src/Views/email_activate_show.php
- src/Views/login.php
- src/Views/magic_link_form.php
- src/Views/register.php
`/` is not needed for HTML5.
**Checklist:**
> refactor: replace `/>` with `>` for input tags

- docs/customization/views.md
- mkdocs.yml
Customizing views is recommended.
**Checklist:**
> docs: add "Customizing Views"

- phpstan-baseline.php
> fix: phpstan errors for phpstan-codeigniter (v1.4.0.70400)

- UPGRADING.md
- composer.json
- docs/getting_started/install.md
- docs/references/authentication/authentication.md
- src/Authentication/Authenticators/Session.php
- src/Authorization/Groups.php
- src/Authorization/Traits/Authorizable.php
- src/Commands/Setup.php
- src/Controllers/ActionController.php
- src/Controllers/LoginController.php
- src/Controllers/MagicLinkController.php
- src/Controllers/RegisterController.php
- src/Filters/ForcePasswordResetFilter.php
- src/Filters/HmacAuth.php
- src/Filters/JWTAuth.php
- src/Filters/SessionAuth.php
- src/Filters/TokenAuth.php
- src/Helpers/email_helper.php
- src/Validation/ValidationRules.php
- tests/Commands/SetupTest.php
- tests/_support/TestCase.php
See https://forum.codeigniter.com/showthread.php?tid=88545 and #872
**Checklist:**
> refactor: remove Composer autoloading of auth helper

- docs/customization/login_identifier.md
> docs: add note for removing email from registration in customization/login_identifier

- .github/workflows/docs.yml
The production date by **mkdocs-git-revision-date-localized-plugin** on local is correct, this is due to local access to **.git**.
Now in the online mode, these dates are displayed incorrectly. This PR is trying to address this issue.
I already tested [here](https://github.com/datamweb/shield-oauth/pull/76).
- fix Last update&Created
- refactor action steps
**Checklist:**
> fix date localized-plugin and refactor action

- src/Language/id/Auth.php
- tests/Language/IndonesianTranslationTest.php
new pull request from #912 
did I do it right this time?
**Checklist:**
> lang: [id] add translation

- UPGRADING.md
- src/Config/Auth.php
- src/Filters/AbstractAuthFilter.php
- src/Filters/GroupFilter.php
- src/Filters/PermissionFilter.php
- tests/Authentication/Filters/GroupFilterTest.php
- tests/Authentication/Filters/PermissionFilterTest.php
See https://forum.codeigniter.com/showthread.php?tid=88262
> feat: add redirect denied for filter

- src/Filters/AbstractAuthFilter.php
- src/Filters/SessionAuth.php
`url_is()` checks the URI path. If the path is changed by devs, it will not work.
**Checklist:**
> fix: replace `url_is()`

- docs/guides/api_hmac_keys.md
- docs/guides/api_tokens.md
Remove unnecessary `/` from routes.
**Checklist:**
> docs: remove unneeded `/` from routes

- docs/customization/route_config.md
- docs/quick_start_guide/using_session_auth.md
- docs/references/controller_filters.md
The duty of **session** is to protect URLs. I think devs should know that there is no reason to protect **logout**. That's why I think we don't need to change the code.
I have already added this topic #642 .
fix #920 
**Checklist:**
> docs: add `logout` to session except list

- phpstan-baseline.php
- src/Auth.php
- src/Authentication/Authentication.php
- src/Config/Services.php
- src/Helpers/auth_helper.php
See https://github.com/codeigniter4/shield/discussions/905#discussioncomment-7285767
- to reduce the number of loaded files
- in the current code, `service('auth')->routes($routes)` creates `Authentication` and `UserModel` instances.
Before:
After:
**Checklist:**
> perf: refactor Auth

- phpstan-baseline.php
see https://github.com/codeigniter4/shield/actions/runs/6600355638/job/17930257377
**Checklist:**
> phpstan: fix phpstan error

- tests/Language/AbstractTranslationTestCase.php
See https://github.com/codeigniter4/shield/pull/954#issuecomment-1817960690
**Checklist:**
> Add test for checking localization parameters are not translated

- tests/Unit/Authentication/JWT/JWTManagerTest.php
It seems the order of array items changed by the library upgrade.
```diff
1) Tests\Unit\Authentication\JWT\JWTManagerTest::testIssueAddHeader
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
Array &0 (
+    'typ' => 'JWT'
'extra_key' => 'extra_value'
-    'typ' => 'JWT'
'alg' => 'HS256'
)
/home/runner/work/shield/shield/tests/Unit/Authentication/JWT/JWTManagerTest.php:186
phpvfscomposer:///home/runner/work/shield/shield/vendor/phpunit/phpunit/phpunit:106
```
https://github.com/codeigniter4/shield/actions/runs/7073301556/job/19253043215?pr=963
**Checklist:**
> test: update assertion in JWTManagerTest

- docs/customization/adding_attributes_to_users.md
- docs/customization/user_provider.md
- add explanations
**Checklist:**
> docs: add explanations to "Adding Attributes to Users"

- UPGRADING.md
- phpstan-baseline.php
- src/Authentication/Authenticators/Session.php
- src/Authentication/Passwords.php
- src/Config/Auth.php
- tests/Authentication/Authenticators/SessionAuthenticatorTest.php
Supersedes  #867
Closes #771
**Checklist:**
> refactor: remove supportOldDangerousPassword

- docs/CNAME
- docs/assets/css/codeigniter.css
- docs/assets/css/codeigniter_dark_mode.css
- mkdocs.yml
This PR updates the docs color scheme to match one from Tasks and Queue projects.
**Checklist:**
> docs: update docs color scheme

- docs/customization/route_config.md
- src/Auth.php
- tests/Unit/AuthRoutesTest.php
If you need to override all of the auth controllers it is a pain to have to specify all of the routes manually when all you need is to change the namespace. This change allows you to pass a `namespace` option along into the `auth()->routes()` call.
```php
auth()->routes($routes, ['namespace' => 'App\Controllers\Auth']);
```
**Checklist:**
> Allow specifying namespace when generating routes.
