composer.lock, docs/1 - authentication.md, docs/2 - auth_actions.md, src/Authentication/Actions/ActionInterface.php, src/Authentication/Actions/Email2FA.php, src/Authentication/Actions/EmailActivator.php, src/Authentication/Traits/HasAccessTokens.php, src/Config/Auth.php, src/Config/AuthRoutes.php, src/Controllers/ActionController.php, src/Controllers/LoginController.php, src/Entities/User.php, src/Language/en/Auth.php, src/Test/AuthenticationTesting.php, src/Views/email_2fa_email.php, src/Views/email_2fa_show.php, src/Views/email_2fa_verify.php, src/Views/email_activate_email.php, src/Views/email_activate_show.php, tests/Controllers/ActionsTest.php, tests/Controllers/LoginTest.php, tests/Controllers/RegisterTest.php
Authentication Actions are a way to standardize email activation, email/SMS-based 2FA, etc.
=> WIP: Authentication Actions

composer.json, src/Auth.php, src/Authentication/AuthenticatorInterface.php, src/Authentication/Handlers/AccessTokens.php, src/Authentication/Handlers/Session.php, src/Authentication/Traits/Authenticatable.php, src/Helpers/auth_helper.php, tests/Authentication/AuthHelperTest.php
This PR makes a few small adjustments to bring `Shield` in line with CodeIgniter 4's [Authentication Implementation](https://codeigniter4.github.io/CodeIgniter4/extending/authentication.html).
=> authentication-implementation

.github/workflows/compare.yml, roave-bc-check.yaml
This workflow is a little finicky sometimes and I'm not sure what it will do in the absence of an actual release so I've split it out from #10
=> Add RoaveBC

composer.json
Switch to released version of Settings dependency.
=> Settings Dependency

src/Controllers/RegisterController.php
input name in view is "pass*word*_confirm"
=> pass_confirm is required

src/Authentication/Handlers/Session.php
Attempt with it status is recorded in attempt() method. Before change every login makes 2 records in auth_logins table.
=> unnecessary call after attempt recorded

src/Authentication/Actions/Email2FA.php, src/Config/AuthRoutes.php, src/Controllers/LoginController.php, src/Views/email_2fa_show.php, src/Views/email_2fa_verify.php, src/Views/login.php, src/Views/register.php
- token (new input name, as is expected in Email2FA)
- right keyboard
- right input mode
- pattern
- set "one-time-code" that could help sometimes
=> Form UX  + named routes + $_SESSION -> session()

docs/3 - auth_actions.md, src/Config/Auth.php
Issue https://github.com/lonnieezell/codeigniter-shield/issues/33 related fix
=> fix auth_actions docs

.github/workflows/deptrac.yml, .github/workflows/infection.yml, .github/workflows/phpcsfixer.yml, .github/workflows/phpstan.yml, .github/workflows/phpunit.yml, .github/workflows/rector.yml, .github/workflows/unused.yml, composer.json, phpstan.neon.dist
Hopefully this gets the GitHub Actions pipeline working correctly again 🤞
=> Workflow Fixes

tests/Controllers/ActionsTest.php
Follow-up: [#49](https://github.com/lonnieezell/codeigniter-shield/pull/49#issuecomment-1103257793)
=> test: fix ActionsTest

src/Authentication/Passwords/NothingPersonalValidator.php, src/Authentication/Passwords/PwnedValidator.php, src/Authentication/Passwords/ValidatorInterface.php
Follow-up: #45
Sorry, there are still deprecated classes.
=> refactor: update Entity classname

tests/Authentication/AccessTokenHandlerTest.php, tests/Authentication/AccessTokenTest.php, tests/Authentication/AuthenticationTest.php, tests/Authentication/HasAccessTokensTest.php, tests/Authentication/SessionFilterTest.php, tests/Authentication/TokenFilterTest.php, tests/Controllers/RegisterTest.php, tests/_support/DatabaseTestCase.php, tests/_support/TestCase.php
- add `DatabaseTestCase`
- remove deprecated `CIDatabaseTestCase`
- fix `TestCase` to use Array Settings Handler
=> test: replace  deprecated CIDatabaseTestCase

composer.json, psalm.xml, psalm_autoload.php, src/Controllers/RegisterController.php, src/Entities/User.php
See https://psalm.dev/
The current type coverage is 81%.
> Psalm was able to infer types for 81.4696% of the codebase
=> chore: add Psalm

src/Authentication/Passwords.php, src/Result.php, tests/Unit/PasswordsTest.php
- fix incorrect Result key
- update PHPDocs
=> fix: incorrect Result key

src/Authentication/Actions/Email2FA.php, src/Authentication/Actions/EmailActivator.php, src/Authentication/Handlers/AccessTokens.php, src/Authentication/Traits/HasAccessTokens.php, src/Controllers/MagicLinkController.php, src/Entities/User.php, src/Filters/SessionAuth.php, src/Models/UserIdentityModel.php, src/Models/UserModel.php
Refactor to revisit the interfaces. This is the first PR.
- Move SQL related to `auth_identities` table to `UserIdentityModel`.
=> refactor: move SQL logic into UserIdentityModel

docs/2 - authentication.md
Ref #67
First, remove **handler** from the documentation.
=> docs: hander -> authenticator

docs/0 - install.md
=> docs: improve install.md

docs/1 - concepts.md
=> docs: Identifier -> Identity

docs/0 - install.md
- update for implemetation change
=> docs: update install.md

src/Authentication/Actions/Email2FA.php, src/Authentication/Actions/EmailActivator.php, src/Config/Auth.php, src/Controllers/LoginController.php, src/Controllers/MagicLinkController.php, src/Controllers/RegisterController.php
I feel uncomfortable with instantiating a controller.
=> refactor: move getLoginRedirect(), getLogoutRedirect(), getRedirectURL() to Config\Auth

src/Authentication/Traits/UserProvider.php, src/Entities/User.php
=> refactor: add private properties in User

src/Views/email_activate_email.php, src/Views/magic_link_email.php, src/Views/magic_link_form.php
1. Corrected the wrong route name used in the magic link email template which resulted in a blank url when sent.
2. Updated the magic link form response to display an error if a wrong or invalid email address is entered.
=> Update to view templates

src/Authentication/AuthenticatorInterface.php, src/Authentication/Handlers/AccessTokens.php, src/Authentication/Handlers/Session.php, src/Authentication/Traits/Authenticatable.php, src/Authentication/Traits/UserProvider.php, src/Entities/User.php, src/Interfaces/Authenticatable.php, src/Interfaces/UserProvider.php, src/Models/LoginModel.php, src/Models/RememberModel.php, src/Models/UserModel.php, tests/Authentication/AuthHelperTest.php
~~Needs to rebase after merging #63~~
It is too strict that only `int` can be used for user object ID.
=> fix: [interface] User ID type

.github/workflows/deptrac.yml, .github/workflows/infection.yml, .github/workflows/phpcsfixer.yml, .github/workflows/phpstan.yml, .github/workflows/phpunit.yml, .github/workflows/rector.yml, .github/workflows/unused.yml
Reverts codeigniter4/shield#87
=> Revert "Use a PAT for hopefully less Github authentication issues."

src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
The code wasn't needed as RDBMS will drop the index when the table is dropped.
=> Remove drop indexes. Fixes #90

src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
- improve readability
- remove unused variable
=> refactor: create_auth_tables migration file

src/Authentication/Traits/HasAccessTokens.php
Ref #65
- add private property
- rename `$activeAccessToken` to `$currentAccessToken`
=> refactor: make private property `User::$activeAccessToken`

deptrac.yaml
=> chore: update deptrac.yaml

admin/pre-commit, composer.json
- update with reference to CodeIgniter4's
=> chore: update composer command and pre-commit

src/Entities/User.php, tests/Unit/UserTest.php
~~Need to rebase after merging #112~~
Fixes #83
Fixes #107 
Supersedes #94
- remove `get*Column()` methods
- remove `identitiesOfType()`
=> refactor: User and UserModel

src/Authentication/Authenticators/Session.php, src/Controllers/LoginController.php, src/Models/RememberModel.php, src/Views/login.php, tests/Authentication/SessionAuthenticatorTest.php
~~Needs to rebase after merging #118~~
=> feat: remember me implementation

src/Models/RememberModel.php
- change return type to void when *command* methods 
- and throw Exception if error occurs
=> refactor: change return type to void in RememberModel

src/Authorization/Models/GroupModel.php, src/Authorization/Models/PermissionModel.php, src/Authorization/Traits/Authorizable.php
- extract GroupModel
- extract PermissionModel
=> refactor: extract Models from Authorizable

src/Auth.php, src/Authentication/AuthenticatorInterface.php, src/Authentication/Authenticators/AccessTokens.php, src/Authentication/Authenticators/Session.php, src/Filters/SessionAuth.php, src/Filters/TokenAuth.php
`recordActive` is difficult to understand the meaning.
=> refactor: change recordActive() to recordActiveDate()

src/Authorization/Traits/Authorizable.php, src/Models/GroupModel.php, src/Models/PermissionModel.php
=> refactor: move Authorization/Models/* -> Models/

src/Entities/User.php
- remove `getRememberToken()` and `setRememberToken()`
=> refactor: remove unused methods in User

src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
=> fix: remove unused `users.permissions`

src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
Fixes #137
It is not needed now.
=> fix: remove auth_reset_attempts table

src/Database/Migrations/2020-12-28-223112_create_auth_tables.php, src/Entities/User.php, src/Models/LoginModel.php, tests/Authentication/AccessTokenAuthenticatorTest.php, tests/Authentication/SessionAuthenticatorTest.php, tests/Controllers/LoginTest.php, tests/Unit/UserTest.php
=> fix: rename `auth_logins.email`

src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
- remove `auth_activation_attempts` (Ref #138)
- remove unique key for `users.email`
- fix the column name for key (Follow-up  #142)
=> update migration file

src/Models/UserIdentityModel.php
Addresses an issue where identity actions are not set resulting in a SQL query error.
Fixes #150
=> Bugfix: Empty Identities

docs/1 - concepts.md, src/Entities/User.php, src/Models/UserModel.php, tests/Unit/UserTest.php
=> Ensures email/password/password_hash are saved when user is saved.

src/Language/en/Auth.php, src/Views/email_2fa_email.php, src/Views/email_2fa_show.php, src/Views/email_activate_email.php, src/Views/email_activate_show.php, src/Views/magic_link_form.php, src/Views/magic_link_message.php, tests/Controllers/ActionsTest.php
When localized and checked, some messages were missing or difficult to understand the meaning.
- add missing lang messages
- fix some lang messages
=> fix: add/improve lang messages

src/Authentication/Actions/CreateIdentityTrait.php, src/Authentication/Actions/Email2FA.php, src/Authentication/Actions/EmailActivator.php, src/Authentication/Authenticators/Session.php, src/Models/CheckQueryReturnTrait.php, src/Models/DatabaseException.php, src/Models/RememberModel.php, src/Models/UserIdentityModel.php, src/Models/UserModel.php, tests/Unit/CreateIdentityTraitTest.php, tests/Unit/UserIdentityModelTest.php
Fixes #143 
- if UNIQUE constraint error occurs, repeat insertion max 5 times.
=> fix: token unique constraint error

src/Language/fa/Auth.php
Hello **engineers!**
The language file was modified for Persian.
(related to PR #160)
=> fix: translate fa-IR 

.github/workflows/phpunit.yml, phpunit.xml.dist, tests/Language/AbstractTranslationTestCase.php, tests/Language/FarsiTranslationTest.php, tests/Language/JapaneseTranslationTest.php
from https://github.com/codeigniter4/translations/tree/develop/tests
=> test: add Translations Tests

src/Auth.php, src/Authentication/Actions/Email2FA.php, src/Authentication/Actions/EmailActivator.php, src/Authentication/Authenticators/AccessTokens.php, src/Authentication/Authenticators/Session.php, src/Controllers/MagicLinkController.php, src/Entities/User.php, src/Models/GroupModel.php, src/Models/PermissionModel.php, src/Models/RememberModel.php, src/Models/UserIdentityModel.php, tests/Authentication/AccessTokenAuthenticatorTest.php, tests/Authentication/ChainFilterTest.php, tests/Authentication/SessionAuthenticatorTest.php, tests/Authentication/SessionFilterTest.php, tests/Authentication/TokenFilterTest.php
~~Need to rebase after merging #161~~
- remove getAuthPassword()
- remove getAuthEmail()
- remove getAuthId()
=> refactor: remove getAuth*()

.github/workflows/psalm.yml, composer.json
- update workflows/psalm.yml
- remove vimeo/psalm
=> chore: update workflows/psalm.yml

src/Authentication/Actions/EmailActivator.php, src/Language/en/Auth.php
- add missing lang item
- fix redirect after email activation
=> Add missing `Auth.registerSuccess`

docs/5 - events.md, src/Controllers/MagicLinkController.php
See https://github.com/codeigniter4/shield/issues/131#issuecomment-1135458512
- add `failedLogin` event
- record failed login attempt
- record successful login
=> feat: Magic Link Login events and logging

docs/2 - authentication.md
- fix title level
- small fixes
Before:
After:
=> docs: fix authentication.md

src/Language/ja/Auth.php
=> fix: add missing `Auth.registerSuccess` for ja

.editorconfig, src/Views/email_2fa_verify.php, src/Views/login.php
Ref https://github.com/codeigniter4/CodeIgniter4/pull/6039
- update editorconfig
- use spaces instead of tabs in Views
=> style: fix indentation in view files

src/Collectors/Auth.php, src/Config/Registrar.php, tests/Collectors/AuthTest.php, tests/_support/FakeUser.php
=> feat: add debug toolbar

phpstan.neon.dist, src/Authentication/Authenticators/AccessTokens.php, src/Authentication/Authenticators/Session.php, src/Models/RememberModel.php, tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php, tests/Authentication/Authenticators/SessionAuthenticatorTest.php, tests/Controllers/RegisterTest.php, tests/Unit/UserTest.php
- refactor for CI4/PHPStan update
=> refactor: update for PHPStan update

docs/0 - install.md, src/Commands/Setup.php, src/Commands/Setup/ContentReplacer.php, tests/Commands/Setup/ContentReplacerTest.php, tests/Commands/SetupTest.php
```
$ php spark shield:setup
```
- install config files: `Auth.php` and `AuthGroups.php`
- update `BaseController` and `routes.php`
TODO:
=> feat: add sheild:setup command for initial setup

rector.php
=> chore: workaroud for rector to break code

src/Controllers/MagicLinkController.php
It is better to send input data to the database after validating it.
=> feat: add email validation in MagicLinkController

docs/7 - customization.md, src/Config/Auth.php, src/Controllers/RegisterController.php
This PR simplifies the validation code during registration and gives us the option to change the rules if needed without the need to extend Controller.
=> feat: allow to use custom validation rules for registration

src/Config/Auth.php, src/Controllers/LoginController.php, src/Models/UserModel.php, src/Views/login.php, tests/Controllers/LoginTest.php
Fixes https://github.com/codeigniter4/shield/issues/237
=> feat: add validation in LoginController

src/Authentication/Authenticators/Session.php, src/Models/LoginModel.php, src/Models/UserIdentityModel.php, tests/Authorization/AuthorizableTest.php, tests/Controllers/LoginTest.php
- use Time::now()
- refactor tests
=> refactor: use Time::now()

src/Views/layout.php
Update with last stable version (5.1.3)
=> Update Bootstrap core CSS

docs/authorization.md
The permissions are saved immediately.
https://github.com/codeigniter4/shield/blob/0b3ecf0be7b85be9584cd093923373b18bcf56d0/src/Authorization/Traits/Authorizable.php#L155
=> docs: remove incorrect description in authorization.md

src/Commands/Setup.php
fix coding style.
It seems php-cs-fixer version up causes GA error:
https://github.com/codeigniter4/shield/runs/7279229470?check_suite_focus=true
=> style: run php-cs-fixer

src/Collectors/Auth.php, src/Config/Auth.php, tests/Collectors/AuthTest.php
Hello friends,
This PR displays **user permissions** in the **debug-toolbar**.
=> feat: add user permissions to debug-toolbar

src/Models/UserModel.php, tests/Unit/UserTest.php
=> fix: UserModel::findById() does not work with withIdentities()

docs/authentication.md, src/Database/Migrations/2020-12-28-223112_create_auth_tables.php
We don't have auth_access_tokens table.
=> fix: remove auth_access_tokens table

src/Controllers/LoginController.php
Hello friends.
I plan to add features to the actions section in the **next PR**.
Therefore, it is necessary to integrate the changes of these PR.
When we have `startUpAction()` why not use it!
=> refactor: use `startUpAction()` in `LoginController()`

README.md, docs/install.md
- add about `Specified key was too long` error
- add `alt`
=> docs: small update

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/planned-work.md
Copied from CodeIgniter4 repository, and tweaked.
=> chore: add issue templete

.github/release.yml
From https://github.com/codeigniter4/CodeIgniter4/blob/develop/.github/release.yml
=> chore: add github/release.yml

src/Authentication/Actions/Email2FA.php, src/Authentication/Actions/EmailActivator.php, src/Controllers/MagicLinkController.php, src/Helpers/email_helper.php
Fixes #330
In this commit, 
* I updated the code to show a more detailed error if an email is not sent
=> Fix email deliverability error log

src/Controllers/ActionController.php
=> Load an auth helper in ActionController

src/Config/Auth.php
=> refactor: remove unused Auth::$views items

docs/customization.md
Hello friends,
- add link for custom validation rules
- add description custom rules for login
And I want to know, will adding `Validation.login` to this section make our documentation better or not?
=> docs: link custom validation rules & add custom rules for login

src/Controllers/MagicLinkController.php, src/Views/magic_link_form.php, tests/Authentication/MagicLinkTest.php, tests/Controllers/MagicLinkTest.php
Fixes: https://github.com/codeigniter4/shield/pull/350#issuecomment-1207656514
=> fix: show validate errors in `magic-link`

docs/install.md, src/Commands/Setup.php
Follow-up #368
- show Skip message once
- small fix for the docs
---
Clean installation and
When `$this->helpers = array_merge($this->helpers, ['auth', 'setting']);` exists: 
---
When `$this->helpers = array_merge($this->helpers, ['setting']);` exists:
=> Improve setup

tests/Controllers/LoginTest.php
Because of `Upgrading friendsofphp/php-cs-fixer (v3.9.5 => v3.10.0)`.
=> style: composer cs-fix (LoginTest.php)

src/Authentication/Authenticators/AccessTokens.php, src/Authentication/Authenticators/Session.php, src/Models/UserModel.php, tests/Authentication/Filters/SessionFilterTest.php, tests/Authentication/Filters/TokenFilterTest.php
Refactor recordActiveDate() to avoid updating the 'updated_at' column.
Fix https://github.com/codeigniter4/shield/discussions/388
=> Refactor record active date

src/Filters/TokenAuth.php
Cannot find this code from the `recordActiveDate()` method definition on IDE.
=> refactor: TokenAuth

docs/quickstart.md
To make consistent.
Registration --> Login --> Logout
=> docs: change section order in quickstart.md

docs/authentication.md
=> docs: fix `revokeAllAccessTokens()` sample code

docs/events.md, docs/session_auth_event_and_logging.md
=> docs: add Session Authenticator Event and Logging

docs/authentication.md, docs/quickstart.md
This should close PR #419  and close PR #420
=> Minor fix for docs

src/Authentication/Passwords/NothingPersonalValidator.php, tests/Unit/NothingPersonalValidatorTest.php
This could fixes #385  and closes #389
=> fix: NothingPersonalValidator strip_explode too sensible

docs/events.md, docs/quickstart.md, docs/session_auth_event_and_logging.md, src/Controllers/MagicLinkController.php, tests/Authentication/MagicLinkTest.php
Provides a temp session variable to allow developers to respond as they choose whenever a user has completed a magic link login.
=> feat: notify devs when user has used magic link login.

composer.json
This PR adds `support ` ~~and `funding `~~ links.
You all work hard for Codeigniter community. 
:green_heart: **Happy Programmers Day!** :green_heart:
=> chore: add support links

tests/Authentication/MagicLinkTest.php
=> style: update coding style

docs/install.md
=> docs: add `auth/a/*` to except list

src/Models/UserModel.php, tests/Unit/UserModelTest.php
=> fix: UserModel cannot save an array

src/Controllers/RegisterController.php
All user input should be validated.
=> fix: set only validated fields to User Entity in RegisterController

.gitignore
Ported the much more thorough `.gitignore` file from CI4 repo.
=> Better gitignore file

docs/install.md
Use `composer` command to change `minimum-stability`.
=> docs: improve installation instruction

.github/workflows/phpunit.yml, composer.json
- add testing with lowest dependency
- update minimun version of settings and vfsstream
- reduce the number of checks (Postgre, SQLSRV, OCI8)
- add PHP 8.2 checks
=> chore: update phpunit.yml

docs/authentication.md, docs/authorization.md, docs/events.md, docs/guides/api_tokens.md, docs/guides/mobile_apps.md, docs/install.md
For consistency and readability.
=> docs: make file paths bold

src/Language/pt-BR/Auth.php, tests/Language/AbstractTranslationTestCase.php, tests/Language/BrazilianTranslationTest.php
Supersedes #615
I had to redo the process.
=> Translate pt-BR

src/Models/UserIdentityModel.php, tests/Authentication/ForcePasswordResetTest.php
See https://github.com/codeigniter4/shield/pull/601#discussion_r1095360689
=> test: fix ForcePasswordResetTest::forceGlobalPasswordReset()

src/Models/UserIdentityModel.php, src/Traits/Resettable.php
- `UserIdentityModel::update()` throws Exception when the update fails
=> refactor: UserIdentityModel::update() throws Exception

.github/workflows/unused.yml
=> chore: fix composer-unused version to aviod setup error

src/Config/Auth.php
=> docs: add note to require filter setting for `last_active`

src/Language/de/Auth.php
German translation for 'needActivate' and 'activationBlocked'
=> [de] Translate new strings

src/Entities/Group.php, tests/Authorization/GroupTest.php
Fixes https://github.com/codeigniter4/shield/issues/648
=> fix: group entity can method

.github/workflows/unused.yml
=> Revert "chore: fix composer-unused version to aviod setup error"

tests/Authentication/Authenticators/AccessTokenAuthenticatorTest.php
See https://github.com/codeigniter4/shield/pull/665#issuecomment-1465333910
=> test: fix failed test because of DST

src/Exceptions/SecurityException.php, src/Exceptions/ValidationException.php
All exceptions by Shield should implement BaseException.
=> fix: incorrect base class for exceptions

src/Language/pt-BR/Auth.php
Add pt-BR translation for JWT authentication.
=> lang: Add pt-BR translation for JWT

src/Auth.php
Updates version references for 1.0.0-beta.6.
=> Prep for 1.0.0-beta.6 release

src/Language/tr/Auth.php
Added 7 new translations.
Changed 1 existing translation for misunderstood.
=> lang: tr - added translations

phpstan.neon.dist, src/Controllers/LoginController.php
resolves #720 
- shield uses type **nozero** and **crypto**
I tried, but it seems to need a change proposal(like always:smile:).
=> fix: phpstan errors

src/Controllers/MagicLinkController.php
=> chore: fix psalm error

docs/authorization.md
From https://forum.codeigniter.com/showthread.php?tid=87513&pid=409817#pid409817
=> docs: fix sample code in authorization.md

src/Authentication/Passwords/NothingPersonalValidator.php
Replace call to PHP 8.0's `str_contains`.
=> fix: simplify extraction of email parts

docs/events.md
=> docs: update events.md

src/Language/id/Auth.php
i have creating new PR for add indonesian translation [#759 ](https://github.com/codeigniter4/shield/pull/759)
Thank you.
=> lang: [id] add indonesian translation

src/Language/sk/Auth.php
This pull request contains changes in the translation of the missing Slovak sentences.
=> lang: [sk] translate missing slovak sentences

admin/RELEASE.md
=> docs: update RELEASE.md

README.md
I would like the important QC tools used to be listed.
=> chore: add status badge for Rector/CS/Psalm

src/Config/Auth.php, src/Filters/SessionAuth.php, tests/Authentication/Filters/SessionFilterTest.php
Supersedes #789
feat: redirect after login to entrance url 
closes #722
=> feat: redirect after login to entrance url

src/Language/ar/Auth.php
Supersedes #804
lang: [ar] update arabic translate
=> lang: [ar] update arabic translate

.github/workflows/smart_commenting.yml
This PR attempts to provide an explanation when the label(GPG/test) is added.
Related to #792
Not exactly what I was looking for, maybe I'll do better in the future.
=> chore: add new GitHub action for smart commenting

README.md
=> docs: fix filename in README

phpstan.neon.dist
=> chore: remove not needed Routes from phpstan exclude

.github/workflows/deptrac.yml, .github/workflows/phpcsfixer.yml, .github/workflows/phpstan.yml, .github/workflows/phpunit.yml, .github/workflows/psalm.yml, .github/workflows/rector.yml, .github/workflows/unused.yml
Follow-up #811
See https://github.com/codeigniter4/.github/issues/14
**Checklist:**
=> chore: fix workflow on section

composer.json, phpstan-baseline.php, phpstan.neon.dist, rector.php, src/Config/Services.php
Add phpstan-codeigniter, add errors to baseline
**Checklist:**
=> chore: add phpstan-codeigniter

src/Controllers/RegisterController.php
Controller may be extended.
See https://codeigniter4.github.io/shield/customization/#extending-the-controllers
**Checklist:**
=> fix: property $table visibility in RegisterController

composer.json, phpstan-baseline.php, tests/Unit/UserTest.php
=> refactor: refactor for phpstan errors

composer.json
Sorts the composer.json
**Checklist:**
=> chore: reformat composer.json

.github/workflows/phpcpd.yml
See https://github.com/codeigniter4/CodeIgniter4/issues/7819
=> chore: use codeigniter4/.github/.github/workflows/phpcpd.yml

docs/user_management/managing_users.md
=> docs: add about `shield:user` command

docs/customization/validation_rules.md
- update validation rules
**Checklist:**
=> docs: update validation rules

mkdocs.yml
https://datamweb.github.io/shield/
**Checklist:**
=> better website for docs

docs/addons/jwt.md, docs/references/authentication/auth_actions.md, docs/references/authorization.md
=> docs: remove space from code

.github/workflows/phpunit-lowest.yml
See https://github.com/codeigniter4/shield/pull/861#issuecomment-1738349341
*No space left on device* in GitHub Actions.
This issue was resolved by https://github.com/codeigniter4/.github/pull/16
- add new phpunit-lowest.yml
**Checklist:**
=> chore: fix phpunit workflow

docs/addons/jwt.md
- update outdated sample code
**Checklist:**
=> docs: update sample LoginController for JWT

.github/workflows/smart-commenting.yml
=> chore: add resolving a merge conflict to smart-commenting

tests/Commands/UserTest.php
See https://github.com/codeigniter4/shield/pull/876#issuecomment-1745792862
**Checklist:**
=> test: fix UserTest assertions for Windows

src/Auth.php
Updates version references for `1.0.0-beta.7`.
**Checklist:**
=> Prep for 1.0.0-beta.7 release

.github/workflows/no-merge-commits.yml
=> chore: fix no-merge-commits.yml

docs/addons/jwt.md, docs/customization/integrating_custom_view_libs.md, docs/getting_started/concepts.md, docs/guides/mobile_apps.md, docs/references/authentication/authentication.md, docs/references/events.md
=> docs: fix small items

docs/customization/adding_attributes_to_users.md, mkdocs.yml
- add docs for "Adding Attributes to Users"
**Checklist:**
=> docs: add "Adding Attributes to Users"

docs/guides/mobile_apps.md
=> docs: fix email rule for mobileLogin

src/Auth.php
https://github.com/lonnieezell/forum-example/actions/runs/6595346385/job/17920264780?pr=100
**Checklist:**
=> happy phpstan for `forget()`

tests/Authentication/Filters/SessionFilterTest.php
This PR is a refactor for testing using Rector.
See https://github.com/codeigniter4/shield/actions/runs/6641954393/job/18045603644
follow-up https://github.com/codeigniter4/shield/pull/929
**Checklist:**
=> test: refactor SessionFilterTest by rector 0.18.6

docs/quick_start_guide/using_session_auth.md, docs/references/controller_filters.md
See https://github.com/codeigniter4/shield/discussions/930#discussioncomment-7384273
**Checklist:**
=> docs: improve on filter aliases

README.md
=> docs: fix forum link

src/Config/AuthGroups.php
=> docs: fix change-available-groups links

src/Config/Auth.php
=> docs: fix protecting-pages link

composer.json, tests/Unit/NothingPersonalValidatorTest.php
1. update rector/rector requirement from 0.18.6 to 0.18.7
2. run rector with **0.18.7**
resolve #947 
**Checklist:**
=> update/run rector from 0.18.6 to 0.18.7

src/Language/ru/Auth.php, tests/Language/RussianTranslationTest.php
See https://github.com/codeigniter4/shield/actions/runs/6932541453/job/18856722242
Follow-up  #925 
**Checklist:**
=> style: fix code styling by cs-fix

src/Auth.php
Updates version references for `1.0.0-beta.8`.
Prev #886
**Checklist:**
=> Prep for 1.0.0-beta.8 release

docs/index.md
In order to keep a consistent look in the docs across all of our sites, I've removed the emoji from the main index.md file of the docs.
=> docs: Remove emojis from index 

src/Views/email_2fa_show.php
- run `composer cs-fix`
**Checklist:**
=> docs: composer cs-fix
